name: movies_challenge
description: "Mobile Coding Challenge for Kueski"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  dio: 5.7.0
  freezed: 2.5.2
  freezed_annotation: 2.4.4
  go_router: 14.6.3
  intl: 0.19.0
  provider: 6.1.2
  retrofit: 4.4.1
  get_it: 8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  build_runner: 2.4.11
  json_serializable: 6.8.0
  retrofit_generator: 9.1.3

flutter:
  generate: true
  uses-material-design: true
